### PR TITLE
Increate default timeouts

### PR DESCRIPTION
**Pull request by tnadler**

### CODE REVIEW

**Review by yonghaoy — APPROVED** [review]

**Review by ddietterich — CHANGES_REQUESTED** [review]
I'd like to understand the rationale here better. I think we need to write this down and get some other eyes on it.

If an http request is taking longer to respond than 30-60 seconds, then there is a protocol problem. Waiting 5 minutes delays failure detection of services that should be retried. To elaborate: suppose we are talking to TDR. We will get a network timeout if a TDR pod goes down. We need to retry in order to failover to a new pod. It should not take us 5 minutes to fail over. It should be more like 30 seconds.

**Comment by tnadler** [comment]
@yonghaoy I would love your thoughts here. I had initially just wanted to increase the retry timeout on the flight itself but yonghao was concerned some operations were quite long lived themselves.

**Comment by tnadler** [comment]
I have lost the thread on this. @yonghaoy @dd - shall I revert this?

**Comment by ddietterich** [comment]
I suggest closing this. It isn't the approach we want to take.

**Pull request closed without merging**
