### PR TITLE
add google cloud profiler client [AS-640]

### PR DESCRIPTION
**Pull request by zarsky-broad**
Copied from [janitor](https://github.com/DataBiosphere/terra-resource-janitor/blob/603db78f0a985e7f64d6feaefa6896e3f1c4dce7/build.gradle#L128) and [buffer](https://github.com/DataBiosphere/terra-resource-buffer/blob/eb26012e4f745ead2c749f6ddc4acc86e953b265/build.gradle#L138)

### CODE REVIEW

**Review by zloery — APPROVED** [review]

**Review by davidangb — APPROVED** [review]
:+1: for code.

What happens in prod if we run this but the APIs are not enabled on the Google project side? Should this wait on DDO-1057 to merge?

**Comment by davidangb** [comment]
also ... I know github actions are stalled right now, but make sure everything passes before merging, of course

**Comment by zarsky-broad** [comment]
TIL: https://coderwall.com/p/vkdekq/git-commit-allow-empty

**Comment by zarsky-broad** [comment]
> What happens in prod if we run this but the APIs are not enabled on the Google project side? Should this wait on DDO-1057 to merge?

I'm honestly not sure. Since prod's not yet used, we could always try it and roll it back if there's an issue.

Also, I was looking at the janitor and buffer jib setups again, I just realized we were using alpine but they weren't, which is [an issue](https://cloud.google.com/profiler/docs/profiling-java#running_with_linux_alpine) since we don't want to have to customize the image, so I've switched us to a Debian base here. Also, neither was building with a blessed image, I'm not sure if there's a reason for that...?

**Comment by ddietterich** [comment]
I'd like more information about the change to the base image before this goes in.

**Comment by zarsky-broad** [comment]
@ddietterich We only changed off of it because we could get away with Alpine and it was lighter, we were running on this for a bit before that, so there have previously been live wsm instances running on Debian.

**Comment by ddietterich** [comment]
I would also like to know why we are using cloud profiler. That comes from security, but it is not a security feature. I would like to understand what features it provides that we do not already get using prometheus.

Perhaps this is an item for our Thursday sync

**Comment by zarsky-broad** [comment]
@davidangb @zloery could you re-thumb with the new base image?

**Review by zloery — APPROVED** [review]

**Comment by davidangb** [comment]
I'd like to see what the resolution to Dan's questions are before approving, especially if something might change

**Comment by ddietterich** [comment]
Resolution to my questions are:
1. Cloud Profiler is not a security requirement. It is lightweight and useful to have.
2. It is running in Janitor and Buffer services and they are also using debian, so this brings WSM into alignment rather than making it unique.
Thanks you for your patience!

**Review by davidangb — APPROVED** [review]
:+1: please make sure to follow this closely to prod to ensure that there are no issues with the relevant API not being enabled!

**Comment by zarsky-broad** [comment]
Just verified, this appears to already be enabled on the prod google project, so I think we don't actually have a problem here.

**Pull request merged**
