### PR TITLE
mark deprecated endpoints as deprecated

### PR DESCRIPTION
**Pull request by zarsky-broad**

### CODE REVIEW

**Review by ddietterich — COMMENTED** [review]
Can we do this post rename merge?

**Comment by zarsky-broad** [comment]
I don't think it really matters _when_ we do it, the primary effects are in the swagger UI and on the documentation on the client methods.

**Comment by zarsky-broad** [comment]
Alternately @ddietterich I think it might be reasonable to roll these changes into that?

**Comment by jaycarlton** [comment]
Where does the deprecated annotation show up? Just Swagger UI?

**Comment by ddietterich** [comment]
OK, I added those marks into the rename PR.

**Comment by zarsky-broad** [comment]
@jaycarlton I think it also adds an `@` annotation on the generated client code.

@ddietterich cool, I'll go ahead and close this!

**Pull request closed without merging**
