### PR TITLE
[PF-1806] Add dsub.

### PR DESCRIPTION
**Pull request by deflaux**

### CODE REVIEW

**Comment by deflaux** [comment]
@yuhuyoyo who should be a second reviewer to this so that it can be merged?

Also, does it make sense that some checks were not successful?

**Review by zloery — APPROVED** [review]
Those are some pretty weird GHA failures - I reran the jobs and it looks like they're failing to read github secrets, I'm guessing this is a github permissions issue (maybe the `verily-terra-solutions` group doesn't have the right permissions here?). I'll follow up in Slack!

**Comment by zloery** [comment]
It looks like team permissions didn't fix this, I'm now wondering if the issue is the interaction of Github secrets with a PR from a fork instead of a branch in the same repo. I recreated this PR in a branch to test.

With the updated permissions changes, you (and anyone else in the solutions team!) should be able to make branches in this repo directly and make PRs from those branches into `main`. Sorry for all the difficulty for a one line change!

**Comment by deflaux** [comment]
closing thanks to https://github.com/DataBiosphere/terra-workspace-manager/pull/717#event-6973116555

**Pull request closed without merging**
