### PR TITLE
WOR-164 - setup snapshots tests on alpha and staging

### PR DESCRIPTION
**Pull request by ungwudik**
https://broadworkbench.atlassian.net/browse/WOR-164

- Create TDR datasets/snapshots alpha and staging (done outside of this PR)
- Setup the snapshots for use in WSM alpha and staging tests.
- Add test for `getDataRepoSnapshotReferenceByName`

### CODE REVIEW

**Review by marctalbott — APPROVED** [review]
All looks good to me

**Review by cahrens — APPROVED** [review]
This looks OK, but I'm not familiar with how these tests work, so I've been somewhat reluctant to be the second thumb.

**Comment by ungwudik** [comment]
> This looks OK, but I'm not familiar with how these tests work, so I've been somewhat reluctant to be the second thumb.

That's good feedback for me. I'll add a reviewer from PF team since they also have context around this test. Obvsiously still good for Workspace team's awareness as we pick up more WSM stuff.

**Review by ddietterich — APPROVED** [review]
lgtm

**Pull request merged**
