### PR TITLE
[PF-1642] Increase timeout for WorkspaceLifecycle integration test

### PR DESCRIPTION
**Pull request by melissachang**
I'm confused at how this test passed. It takes more than 5 seconds to create a workspace...

### CODE REVIEW

**Review by ddietterich — APPROVED** [review]
Good catch.

**Review by zloery — APPROVED** [review]
From looking at previous test runs, it looks like this actually does run in ~3 seconds. The test makes 3 sync calls to WSM (create, patch, delete) and the workspace it creates doesn't have any cloud context attached (which is normally where most of the time is spent). But 1m is probably a better limit, I don't know why the old one was so low

**Comment by melissachang** [comment]
> From looking at previous test runs, it looks like this actually does run in ~3 seconds. The test makes 3 sync calls to WSM (create, patch, delete) and the workspace it creates doesn't have any cloud context attached (which is normally where most of the time is spent). But 1m is probably a better limit, I don't know why the old one was so low

Ahh thanks. There's no spend profile in the request, so cloud context isn't created.

Now that I understand there's no cloud context created, I changed to 10 seconds, that should be enough. Thanks.

**Comment by zloery** [comment]
> Ahh thanks. There's no spend profile in the request, so cloud context isn't created.
> 
> Now that I understand there's no cloud context created, I changed to 10 seconds, that should be enough. Thanks.

It's not just the spend profile, at the WSM level creating a cloud context is actually a separate (and async) API call (`POST /api/workspaces/v1/{workspaceId}/cloudcontexts`), we just hide that at the UI/CLI layer.

10 seconds sgtm, thanks for this!

**Comment by melissachang** [comment]
> It's not just the spend profile, at the WSM level creating a cloud context is actually a separate (and async) API call (`POST /api/workspaces/v1/{workspaceId}/cloudcontexts`), we just hide that at the UI/CLI layer.

I did not know that. TIL. Thanks!

**Pull request merged**
