### PR TITLE
[no ticket] update instructions for Main config

### PR DESCRIPTION
**Pull request by jaycarlton**
Instructions needed a refresh post-re-gradliing. The run directory and env var needed updates. Added an image.

### CODE REVIEW

**Comment by zarsky-broad** [comment]
I'm no longer on a team working on wsm, so you should probably find a different reviewer. <3

**Comment by jaycarlton** [comment]
But you're the leading expert 💕

**Comment by zarsky-broad** [comment]
I'm investigating some relevant stuff for my new app, so hang tight for like a day and I might have some useful contribution?

**Comment by zarsky-broad** [comment]
(I accept your heart emoji bribe)

**Review by ddietterich — APPROVED** [review]
Thank you! I will use this at some point and now I don't have to try to remember it

**Comment by zarsky-broad** [comment]
Try checking the "store as project file" box in the config window. Then intellij will autoimport it for others.

**Comment by jaycarlton** [comment]
> Try checking the "store as project file" box in the config window. Then intellij will autoimport it for others.

What other projects would I want this config to live in?

**Comment by zarsky-broad** [comment]
Ah, not for other projects, for other people. It gets checked in to the repo.

**Comment by jaycarlton** [comment]
I'm not sure it's saving the whole configuration when I do that. 
```
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Main" type="SpringBootApplicationConfigurationType" factoryName="Spring Boot">
    <module name="terra-workspace-manager.service.main" />
    <option name="SPRING_BOOT_MAIN_CLASS" value="bio.terra.workspace.app.Main" />
    <option name="ALTERNATIVE_JRE_PATH" />
    <method v="2">
      <option name="Make" enabled="true" />
    </method>
  </configuration>
</component>
```

**Review by zarsky-broad — APPROVED** [review]
Only comment is that it's convenient to enable the JMX agent in the run config.

**Pull request merged**
