### PR TITLE
[PF-352] Create code owners for WM

### PR DESCRIPTION
**Pull request by ddietterich**
Starting point for code owners for WM

### CODE REVIEW

**Review by zloery — APPROVED** [review]
LGTM for the set from PF.

Once we have this, do we need to require codeowners approval of PRs separately? It might be redundant given the 2 reviewer requirement

**Review by davidangb — APPROVED** [review]

**Comment by davidangb** [comment]
fyi @zarsky-broad since you brought up this same issue

**Comment by ddietterich** [comment]
We might be able to craft a rule that required that reviews be done by codeowners. Do folks think that would be desirable?

**Comment by davidangb** [comment]
@ddietterich it's absolutely possible, inside the github branch protection rules (doc: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/about-required-reviews-for-pull-requests).  That said ... I don't personally think it's necessary to enforce.

**Pull request merged**
