### PR TITLE
IA-3120 IA-3390 Take an optional resource ID

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-3120

### CODE REVIEW

**Review by ddietterich — APPROVED** [review]
That was easier than I expected. Nice!

**Comment by Qi77Qi** [comment]
@ddietterich do we need to do any duplicate check? Or that'll be handled properly already?

**Comment by ddietterich** [comment]
> do we need to do any duplicate check? Or that'll be handled properly already?

Good point. The create will fail because the UUID is a primary key, but the error may not be pretty - probably a 500 as opposed to a 400 - so maybe check the DAO to see what it throws for a PK collision on the resource table.

You should also add a test to cause duplicate UUIDs and verify they are being properly handled.

**Review by rtitle — APPROVED** [review]
Looks good to me

**Comment by Qi77Qi** [comment]
@ddietterich  gotcha..I'm gonna add a TODO for now since it will fail anyway. Really trying to get sth else working

**Comment by ddietterich** [comment]
Please add a ticket to the TODO and we are good.

**Review by jaycarlton — APPROVED** [review]
Looks like @ddietterich's refactoring crusades are really paying off. This should have been harder.

**Pull request merged**
