### PR TITLE
aj-582 sql to change rawls snapshots-by-reference to copy_reference

### PR DESCRIPTION
**Pull request by calypsomatic**
Migrate existing Rawls snapshots-by-reference to have `COPY_REFERENCE` cloning instructions so they can be cloned along with the workspace.

### CODE REVIEW

**Comment by davidangb** [comment]
Make sure that broadinstitute/rawls#2081 is in prod before this goes to prod!

**Comment by aherbst-broad** [comment]
@calypsomatic the sql looks ok, you'll need to add this to [this](https://github.com/DataBiosphere/terra-workspace-manager/blob/main/service/src/main/resources/db/changelog.xml) list

**Review by ddietterich — APPROVED** [review]
How have you tested this?

**Comment by calypsomatic** [comment]
> How have you tested this?

I did, locally.  However, we de-prioritized this ticket and stopped work on it!

**Comment by ddietterich** [comment]
OK, that doesn't make sense to me. You are one review from finishing.

**Comment by davidangb** [comment]
@calypsomatic I don't see any reason to not merge this. We deprioritized work on other cloning work due to the user demand - but this one is a clear improvement and good to merge (after another thumb and after broadinstitute/rawls#2081 reaches prod)

**Comment by ddietterich** [comment]
Can we close this?

**Comment by calypsomatic** [comment]
> Can we close this?

We may as well.  If we ever return to this ticket we can reopen or reproduce.

**Pull request closed without merging**
