### PR TITLE
[PF-505] workspaceId instead of Id

### PR DESCRIPTION
**Pull request by jaycarlton**

### CODE REVIEW

**Review by davidangb — APPROVED** [review]
lgtm! I see that at least one test failed, I haven't tried to investigate those, just make sure those aren't "real" failures due to this PR.

**Comment by jaycarlton** [comment]
The test failure is repeatable, and only on this branch apparently. I just did a fake PR using dev and it passed everything.

**Review by zarsky-broad — APPROVED** [review]
Fine with this, but only with a version bump, since this will require a change in the use of the swagger client lib.

**Review by zloery — COMMENTED** [review]
I don't think this actually needs a version bump - the names of path variables aren't visible to clients, so nothing needs to change on their end.
The test failures are probably the controllers specifying `PathVariable("id")`, which also need to be changed. But that should also fail the client tests and those passed, so I'm gonna do a bit of digging

**Comment by zarsky-broad** [comment]
> I don't think this actually needs a version bump - the names of path variables aren't visible to clients, so nothing needs to change on their end.
Ah, I was getting confused with `CreateWorkspaceRequestBody`, nvm

**Comment by jaycarlton** [comment]
publiished new version just now

**Pull request merged**
