### PR TITLE
[TERRA-537] Split test.ControlledResourceFixtures to cloud specific classes

### PR DESCRIPTION
**Pull request by dexamundsen**
Current set up - class ControlledResourceFixtures has Azure, GCP and flex (non-cloud specific) resource fixtures

Changes - 

- Split the large file into cloud specific classes
- Non-cloud specific functions and constants are retained in the same file
- Consolidate Azure batch pool functions and constants into ControlledAzureResourceFixtures 

In subsequent PR AWS specific fixtures will be added in a new file

Other - remove unnecessary 'throws' in test functions

Coordinate with -- https://github.com/DataBiosphere/terra-workspace-manager/pull/1273
---

No functional changes. No tests are changed

### CODE REVIEW

**Comment by dexamundsen** [comment]
Rebase and merge after - https://github.com/DataBiosphere/terra-workspace-manager/pull/1273

**Comment by ddietterich** [comment]
Can we push this off to the next sprint? I have a sequence of 3 substantial PRs that this will disrupt.

**Comment by dexamundsen** [comment]
> Can we push this off to the next sprint? I have a sequence of 3 substantial PRs that this will disrupt.

Sure, moving back to draft

**Comment by ddietterich** [comment]
> Sure, moving back to draft
Thank you!

**Comment by dexamundsen** [comment]
Moved to https://github.com/DataBiosphere/terra-workspace-manager/pull/1307

**Pull request closed without merging**
