### PR TITLE
AJ-[768] bump landing zone service version

### PR DESCRIPTION
**Pull request by jordansafer**
Bumping the landing zone service version to include latest changes making kubernetes cluster configurable

### CODE REVIEW

**Review by davidangb — APPROVED** [review]

**Comment by jordansafer** [comment]
Connected test is failing, this appears to be unrelated, and potentially due to a google issue. 5 tests are failing:
```
ControlledGcpResourceApiControllerGcsBucketTest > initializationError FAILED
    com.google.cloud.storage.StorageException at ControlledGcpResourceApiControllerGcsBucketTest.java:145
        Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException at 
```

**Comment by jordansafer** [comment]
Reading through the latest threads, I see the ongoing GCP fire from increases in permission propagation times. This PR is part of an effort to make LZ testing easier in the lead up to the 1/25 preview, will update as I see updates with the GCP/firefighting effort

**Comment by aherbst-broad** [comment]
@jordansafer You'll want to merge main to get fixes dd has pushed up. Azure connected tests are failing due to a test MRG going away, this [PR](https://github.com/DataBiosphere/terra-workspace-manager/pull/1009) should fix it. -- you'll want to merge in that fix as well.

**Comment by rtitle** [comment]
FYI I just rebased this guy and changed the target to `main`. Am deploying it to a BEE to test with https://github.com/broadinstitute/firecloud-develop/pull/3212.

**Comment by rtitle** [comment]
Testing this on a BEE with https://github.com/broadinstitute/firecloud-develop/pull/3212, I'm getting the new machine type and IP configuration, but AKS autoscaling is still disabled and node count is set to 1. Looking into why.

**Comment by jordansafer** [comment]
> Testing this on a BEE with [broadinstitute/firecloud-develop#3212](https://github.com/broadinstitute/firecloud-develop/pull/3212), I'm getting the new machine type and IP configuration, but AKS autoscaling is still disabled and node count is set to 1. Looking into why.

It's possible that the autoscaling config is overridden by the nodecount. Right now, we both set the nodecount (default set it to 1), AND if autoscaling is enabled, we set autoscaling min and max. I'm wondering if the expectation is that we only set 1 or the other. See here where we set AKS nodecount in all cases (and maybe it should only happen in the "else" case of the if-statement below:
https://github.com/DataBiosphere/terra-landing-zone-service/blob/main/service/src/main/java/bio/terra/landingzone/library/landingzones/definition/factories/CromwellBaseResourcesFactory.java#L289

**Comment by rtitle** [comment]
Not sure, the fluent API seems to guide through setting a nodeCount and _then_ autoscaling. The CLI samples also set both:   https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler#create-an-aks-cluster-and-enable-the-cluster-autoscaler

My 2 LZs pretty clearly have 1 node w/ autoscaling disabled though. 🤔 Thinking of trying to get a smaller repro in a LZ service test to try and isolate it..

**Comment by rtitle** [comment]
Fix: https://github.com/DataBiosphere/terra-landing-zone-service/pull/45 😅 

Thinking we can get the LZ PR in, then update this PR to bump to the latest LZ version, and retest.

**Comment by rtitle** [comment]
Udpated, will merge after tests. 

Testing on a BEE in parallel.

**Review by jordansafer — COMMENTED** [review]
Approved 👍

**Pull request merged**
