### PR TITLE
update gitignore

### PR DESCRIPTION
**Pull request by ungwudik**
- gitignore properties file for integration tests
- update todo

### CODE REVIEW

**Comment by zarsky-broad** [comment]
Does it make sense to create e.g. `src/test/resources/rendered`, and we can put this properties file there, along with the other things that are currently rendered to `/tmp/` when running the setup script, and then ignore the folder's contents?

**Comment by ungwudik** [comment]
> Does it make sense to create e.g. `src/test/resources/rendered`, and we can put this properties file there, along with the other things that are currently rendered to `/tmp/` when running the setup script, and then ignore the folder's contents?

**Comment by ungwudik** [comment]
Mistakenly closed this PR, but reopened now!

**Comment by ungwudik** [comment]
> Does it make sense to create e.g. `src/test/resources/rendered`, and we can put this properties file there, along with the other things that are currently rendered to `/tmp/` when running the setup script, and then ignore the folder's contents?

Yes, that's similar to what David An just suggested in Slack. I can add the 'rendered' directory or whatever we'd like to name it.
I'm a little hesitant on moving the service-account json secret file in `/tmp` though. I like the idea that the file in /tmp is cleared by a local system job every now and then.
Also, I know we can gitignore that file when it's under `src` directory, but does that presents an opportunity (although not likely) for the json secret file to accidentally end up in source control due to human error or something else? Especially given that the human user never interacts with json secret file directly.

**Comment by zarsky-broad** [comment]
I think I mainly don't like the idea of a script writing a file to a location that isn't within my user purview. That said, I think you can probably merge this as-is, and we can think about refactoring later.

**Comment by ungwudik** [comment]
> I think I mainly don't like the idea of a script writing a file to a location that isn't within my user purview. That said, I think you can probably merge this as-is, and we can think about refactoring later.

Created AS-397 for the refactor.

**Pull request merged**
