### PR TITLE
[READY FOR REVIEW] QA-1327: GitHub Action to run Workspace Manager tests.

### PR DESCRIPTION
**Pull request by ichengchang**
This branch is spawned from QA-1288. 
The purpose is move the GitHub Action work (QA-1327) into this PR.

Only `.github/workflows/test-runner-perf.yml` need to be reviewed.
Steps to build local WSM client are included In the GutHub Action.

### CODE REVIEW

**Comment by davidangb** [comment]
@ichengchang could you explain "Only .github/workflows/test-runner-perf.yml need to be reviewed."? This PR has 22 changed files, it can't be merged as-is unless everything is  reviewed.

**Comment by ichengchang** [comment]
> @ichengchang could you explain "Only .github/workflows/test-runner-perf.yml need to be reviewed."? This PR has 22 changed files, it can't be merged as-is unless everything is reviewed.

The rest of the changed files are already part of PR https://github.com/DataBiosphere/terra-workspace-manager/pull/156, which is also under review. Since `test-runner-perf.yml` has a dependency on these other files, I need to include them as well in this PR.

**Comment by davidangb** [comment]
test-runner-perf.yml also exists in #156, with only 3 lines different between this PR and that one. Could you consolidate those three lines to be where you want them, close this, and we'll only review #156?

**Comment by davidangb** [comment]
did you mean for this PR to be `QA-1327 -> iv-1288-1`, not `QA-1327 -> dev`?

**Comment by ichengchang** [comment]
> did you mean for this PR to be `QA-1327 -> iv-1288-1`, not `QA-1327 -> dev`?

I've updated the base branch to `iv-1288-1` to make it less confusing. So now only one file appears in this PR.

**Comment by ichengchang** [comment]
> > did you mean for this PR to be `QA-1327 -> iv-1288-1`, not `QA-1327 -> dev`?
> 
> I've updated the base branch to `iv-1288-1` to make it less confusing. So now only one file appears in this PR.

After discussion with Mariko, we thought it would make sense to wait until the test reporting framework is integrated as part of the automated testing workflow. I am closing this PR until the reporting framework is ready.

**Pull request closed without merging**
