### PR TITLE
PF-1244: fix a typo to make sure that the attributes field is required as intended

### PR DESCRIPTION
**Pull request by yuhuyoyo**
GcpBigQueryDatasetResource should have the attributes field set as required.

### CODE REVIEW

**Review by marikomedlock — COMMENTED** [review]
Change lgtm.

Also I think this object is only used in response objects and so we don't expect any new validation errors in clients as a result of this change. Is that correct?

**Comment by yuhuyoyo** [comment]
> 

right. it's only used in response.

**Comment by yuhuyoyo** [comment]
oops made change on the wrong branch. please do not review

**Review by ddietterich — APPROVED** [review]
LGTM

**Pull request merged**
