### PR TITLE
Cleanup after config overhaul [post- AS-396]

### PR DESCRIPTION
**Pull request by zarsky-broad**
Depends on https://github.com/broadinstitute/firecloud-develop/pull/2295

### CODE REVIEW

**Review by davidangb — APPROVED** [review]
:+1: code looks fine. Does this change overall mean that any pre-existing snapshot references - which probably used `terra-dev` - are now broken? If so, make sure to communicate that to any dev team that might have pre-existing references

**Comment by zarsky-broad** [comment]
> 👍 code looks fine. Does this change overall mean that any pre-existing snapshot references - which probably used `terra-dev` - are now broken? If so, make sure to communicate that to any dev team that might have pre-existing references

I'm not sure! @zloery, any insight?

**Comment by zloery** [comment]
> > 👍 code looks fine. Does this change overall mean that any pre-existing snapshot references - which probably used `terra-dev` - are now broken? If so, make sure to communicate that to any dev team that might have pre-existing references
> 
> I'm not sure! @zloery, any insight?

It won't break the DB since we store entire serialized references. I don't actually know if it breaks existing snapshots - does Rawls verify the data repo instance when it looks up snapshots in WM? 
If not, existing snapshots will just have a different value, and it won't cause problems as it's not used after reference creation.

**Comment by zarsky-broad** [comment]
Looks like this will break things, yeah. @davidangb I'm going to go ahead and merge this, since the deed is already done, but any idea who I should give a heads up to?

**Pull request merged**
